.PHONY: all clean install uninstall
all:
	@make -C src
	@make -C src/df_neo
	@make -C sample_new
clean:
	@make -C src clean
	@make -C src/df_neo clean
	@make -C sample_new clean
install:
	@make -C src install
	@make -C src/df_neo install
	@make -C sample_new install
uninstall:
	@make -C src uninstall
	@make -C src/df_neo uninstall
	@make -C sample_new uninstall

