#/******************************************************************************
# *    Copyright (c) 2009-2012 by Hisi.
# *    All rights reserved.
# * ***
# *    Create by Czyong. 2012-09-07
# *
#******************************************************************************/

CROSS_COMPILE ?= arm-hisiv200-linux-

CPU    := hi3716cv100
COBJS  := ddr_training.o

include ../ddr_training.mk

