#ifndef __DRV_HDMI_IOCTL_H__
#define __DRV_HDMI_IOCTL_H__

//#include "hi_common_id.h"
#include "hi_module.h"
//#include "hi_common_log.h"
#include "hi_debug.h"

#include "hi_unf_hdmi.h"
#include "hi_error_mpi.h"
#include "hi_mpi_ao.h"
#include "hi_drv_hdmi.h"

#ifdef __cplusplus
#if __cplusplus
	extern "C"{
#endif
#endif



enum hiIOCTL_HDMI_E
{
    IOCTL_HDMI_INIT = 0X01,
    IOCTL_HDMI_DEINIT,
    IOCTL_HDMI_OPEN,
    IOCTL_HDMI_CLOSE,
    IOCTL_HDMI_START,
    IOCTL_HDMI_STOP,
    IOCTL_HDMI_SINK_CAPABILITY,
    IOCTL_HDMI_POLL_EVENT,
    IOCTL_HDMI_GET_ATTR,
    IOCTL_HDMI_SET_ATTR,
    IOCTL_HDMI_GET_INFORFRAME,
    IOCTL_HDMI_SET_INFORFRAME,
    IOCTL_HDMI_AVMUTE,
    IOCTL_HDMI_VIDEO_TIMING,
    IOCTL_HDMI_GET_DEEPCOLOR,
    IOCTL_HDMI_SET_DEEPCOLOR,
    IOCTL_HDMI_XVYCC,
    IOCTL_HDMI_SET_CEC,
    IOCTL_HDMI_GET_CEC,
    IOCTL_HDMI_CECSTATUS,
    IOCTL_HDMI_PRE_VIDEO_TIMING,
    IOCTL_HDMI_FORCE_GET_EDID,
	IOCTL_HDMI_READ_EDID,
    IOCTL_HDMI_GET_HDMI_PLAYSTAUS,
    IOCTL_HDMI_CEC_ENABLE,
    IOCTL_HDMI_CEC_DISABLE,
    IOCTL_HDMI_REG_CALLBACK_FUNC,
    IOCTL_HDMI_LOADKEY,
    IOCTL_HDMI_GET_PROCID,
    IOCTL_HDMI_RELEASE_PROCID,
    IOCTL_HDMI_GET_AO_ATTR,
    IOCTL_HDMI_AUDIO_CHANGE,
    IOCTL_HDMI_GET_STATUS,
    IOCTL_HDMI_GET_DELAY,
    IOCTL_HDMI_SET_DELAY,
    IOCTL_HDMI_MAX,
};

/*
**IOCTRL Between User/Kernel Level
*/
#define CMD_HDMI_INIT                _IOWR(HI_ID_HDMI, IOCTL_HDMI_INIT,           HDMI_INIT_S)
#define CMD_HDMI_DEINIT              _IOWR(HI_ID_HDMI, IOCTL_HDMI_DEINIT,         HDMI_DEINIT_S)
#define CMD_HDMI_OPEN                _IOWR(HI_ID_HDMI, IOCTL_HDMI_OPEN,           HDMI_OPEN_S)
#define CMD_HDMI_CLOSE               _IOWR(HI_ID_HDMI, IOCTL_HDMI_CLOSE,          HDMI_CLOSE_S)
#define CMD_HDMI_START               _IOWR(HI_ID_HDMI, IOCTL_HDMI_START,          HDMI_START_S)
#define CMD_HDMI_STOP                _IOWR(HI_ID_HDMI, IOCTL_HDMI_STOP,           HDMI_STOP_S)
#define CMD_HDMI_SINK_CAPABILITY     _IOWR(HI_ID_HDMI, IOCTL_HDMI_SINK_CAPABILITY,HDMI_SINK_CAPABILITY_S)
#define CMD_HDMI_POLL_EVENT          _IOWR(HI_ID_HDMI, IOCTL_HDMI_POLL_EVENT,     HDMI_POLL_EVENT_S)
#define CMD_HDMI_GET_ATTR            _IOWR(HI_ID_HDMI, IOCTL_HDMI_GET_ATTR,       HDMI_PORT_ATTR_S)
#define CMD_HDMI_SET_ATTR            _IOWR(HI_ID_HDMI, IOCTL_HDMI_SET_ATTR,       HDMI_PORT_ATTR_S)
#define CMD_HDMI_GET_INFORFRAME      _IOWR(HI_ID_HDMI, IOCTL_HDMI_GET_INFORFRAME, HDMI_INFORFRAME_S)
#define CMD_HDMI_SET_INFORFRAME      _IOWR(HI_ID_HDMI, IOCTL_HDMI_SET_INFORFRAME, HDMI_INFORFRAME_S)
#define CMD_HDMI_SET_AVMUTE          _IOWR(HI_ID_HDMI, IOCTL_HDMI_AVMUTE,         HDMI_AVMUTE_S)
#define CMD_HDMI_VIDEO_TIMING        _IOWR(HI_ID_HDMI, IOCTL_HDMI_VIDEO_TIMING,   HDMI_VIDEOTIMING_S)
#define CMD_HDMI_GET_DEEPCOLOR       _IOWR(HI_ID_HDMI, IOCTL_HDMI_GET_DEEPCOLOR,  HDMI_DEEPCOLORC_S)
#define CMD_HDMI_SET_DEEPCOLOR       _IOWR(HI_ID_HDMI, IOCTL_HDMI_SET_DEEPCOLOR,  HDMI_DEEPCOLORC_S)
#define CMD_HDMI_SET_XVYCC           _IOWR(HI_ID_HDMI, IOCTL_HDMI_XVYCC,          HDMI_SET_XVYCC_S)
#define CMD_HDMI_GET_CEC             _IOWR(HI_ID_HDMI, IOCTL_HDMI_GET_CEC,        HDMI_CEC_S)
#define CMD_HDMI_SET_CEC             _IOWR(HI_ID_HDMI, IOCTL_HDMI_SET_CEC,        HDMI_CEC_S)
#define CMD_HDMI_CECSTATUS           _IOWR(HI_ID_HDMI, IOCTL_HDMI_CECSTATUS,      HDMI_CEC_STATUS)
#define CMD_HDMI_PREVTIMING          _IOWR(HI_ID_HDMI, IOCTL_HDMI_PRE_VIDEO_TIMING,    HDMI_PREVIDEOTIMING_S)
#define CMD_HDMI_FORCE_GET_EDID      _IOWR(HI_ID_HDMI, IOCTL_HDMI_FORCE_GET_EDID,      HDMI_EDID_S) 
#define CMD_HDMI_READ_EDID           _IOWR(HI_ID_HDMI, IOCTL_HDMI_READ_EDID,        HDMI_EDID_S) 
#define CMD_HDMI_GET_HDMI_PLAYSTAUS  _IOWR(HI_ID_HDMI, IOCTL_HDMI_GET_HDMI_PLAYSTAUS,  HDMI_PLAYSTAUS_S) 
#define CMD_HDMI_CEC_ENABLE          _IOWR(HI_ID_HDMI, IOCTL_HDMI_CEC_ENABLE,     HDMI_CEC_ENABlE_S) 
#define CMD_HDMI_CEC_DISABLE         _IOWR(HI_ID_HDMI, IOCTL_HDMI_CEC_DISABLE,    HDMI_CEC_DISABLE_S) 
#define CMD_HDMI_REG_CALLBACK_FUNC   _IOWR(HI_ID_HDMI, IOCTL_HDMI_REG_CALLBACK_FUNC, HDMI_REGCALLBACKFUNC_S) 
#define CMD_HDMI_GET_PROCID          _IOWR(HI_ID_HDMI, IOCTL_HDMI_GET_PROCID,       HDMI_GET_PROCID_S)
#define CMD_HDMI_RELEASE_PROCID      _IOWR(HI_ID_HDMI, IOCTL_HDMI_RELEASE_PROCID,   HDMI_GET_PROCID_S)
#define CMD_HDMI_GET_AO_ATTR         _IOWR(HI_ID_HDMI, IOCTL_HDMI_GET_AO_ATTR,      HDMI_GETAOATTR_S)
#define CMD_HDMI_AUDIO_CHANGE        _IOWR(HI_ID_HDMI, IOCTL_HDMI_AUDIO_CHANGE,     HDMI_GETAOATTR_S)
#define CMD_HDMI_GET_STATUS          _IOWR(HI_ID_HDMI, IOCTL_HDMI_GET_STATUS,       HDMI_STATUS_S)
#define CMD_HDMI_GET_DELAY           _IOWR(HI_ID_HDMI, IOCTL_HDMI_GET_DELAY,        HDMI_DELAY_S)
#define CMD_HDMI_SET_DELAY           _IOWR(HI_ID_HDMI, IOCTL_HDMI_SET_DELAY,        HDMI_DELAY_S)


#ifdef __cplusplus
#if __cplusplus
}
#endif
#endif

#endif

