#
# drivers/mtd/nand/hisfc400/Makefile
#

obj-$(CONFIG_MTD_NAND_HISFC400) += hisfc400.o hisfc400_os.o hisfc400_match.o \
				   hisfc400_ecc_info.o hisfc400_gen.o \
				   hisfc400_spi_general.o hisfc400_spi_giga.o


